
name: Publish

on:
  push:
    tags:
       - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: init python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: build package
      run: |
       python3 -m build --out dist/ 
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}