
name: Release

on:
  push:
    tags:
       - '*'
jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "requirements.txt,pyjsonedit/*"
        token: ${{ secrets.GITHUB_TOKEN }}
